### ISSUE TITLE
Docker Image Has Dependency Issues

### ISSUE THREAD

**Issue by umerhuzaifa** [namheegordonkim/l2cds#1]
Hi Nam,

I have pulled the Docker image and cloned the repository as well. However, I am unable to run the toy_examples mentioned in their folder. (see attached image). Looks like the dependencies are not met in the Docker image. It could very well be something I am unaware of in my use of Docker but just wanted to bring up to make sure. :)
<img width="602" alt="Screen Shot 2020-06-16 at 3 19 39 PM" src="https://user-images.githubusercontent.com/7833132/84818692-e3f35200-afe4-11ea-9daa-f92c95a35722.png">

**Comment by namheegordonkim** [comment]
Hi,

Could you try running the code outside the `toy_examples` directory, i.e.

`python3 toy_examples/shapes_simulate.py`

and see if it works?

**Comment by umerhuzaifa** [comment]
Thanks. 

I am still seeing the same error. Somehow the utils module is not seen.

<img width="628" alt="Screen Shot 2020-06-17 at 5 26 48 PM" src="https://user-images.githubusercontent.com/7833132/84952674-57b65d00-b0c0-11ea-9a9c-4fb9e95e75db.png">

**Comment by umerhuzaifa** [comment]
I think I figured it out. PYTHONPATH needs to know the parent directory 'l2cds'. Also, for displaying the results, PyQt5 package needs to be installed.
