### ISSUE TITLE
Docker toy example still slow

### ISSUE THREAD

**Issue by ashley-holton** [namheegordonkim/l2cds#3]
So after a few days of fiddling with the docker, I know that it is utilizing CUDA, I see the GPU is in use by python when I run the training, and it still takes 100 seconds per iteration of training. I'm trying to get the program set up locally to see if it's just the docker, but in the meantime I was wondering if anyone has actually gotten it to run fast from within the docker? Searching around online makes it seem like other people have experienced pytorch training to be really slow inside a docker, but not on their local machine.

_Originally posted by @ashley-holton in https://github.com/namheegordonkim/l2cds/issues/2#issuecomment-946124585_

**Comment by namheegordonkim** [comment]
@ashley-holton @sheim Thanks kindly for your comments.

> I'm trying to get the program set up locally to see if it's just the docker, but in the meantime I was wondering if anyone has actually gotten it to run fast from within the docker?

I'm suspecting that the old version of PyTorch isn't utilizing your GPU properly. To avoid more issues, I'll go ahead and make some changes to the container and code. Please give me up to 48 hours to get this running.

> Just to chime in, could you post the output of a `pip list` on a working set-up (or the equivalent with whatever environment management you use)?

Good point. When I set up this repo, I had a conda environment that had a bunch of irrelevant packages and didn't want to go through the list, hence sharing the container instead. There are also OS-level dependencies (e.g. libopenapi), which will still require some struggle to install. I'll do these:

1. Create a clean conda environment and list python-specific dependencies in something like a `requirements.txt`
2. Improve the README to help you install additional dependencies
